### ISSUE TITLE
Specify divide-by-zero semantics

### ISSUE THREAD

**Issue by sampsyo** [sampsyo/bril#139]
The Bril docs don't say anything about what divide-by-zero should do, either in the core instructions or in the floating point extension. Options include:

* Undefined behavior.
* Evaluate to zero (or NaN in the FP extension).
* Must crash with an exception.

Crashing with an exception is in some ways the most reasonable thing to do (and models many real languages), but it has two drawbacks:

* Exceptions are otherwise not a thing in Bril, so this would be a new concept.
* It makes basic manipulations more complex because you have to worry about potential side effects for `div` and `fdiv` instructions.

Of course, you can see the latter disadvantage as an advantage, pedagogically speaking… since it introduces an extra nuance, especially for speculative optimizations, that otherwise wouldn't exist in the language.

**Comment by Pat-Lafon** [comment]
For the floating point extension, it seems reasonable to me that division-by-zero follows 64 bit IEEE 754 semantics since the documentation seemingly suggests that they can be treated as such. Both interpreters already follow these semantics. (So possible values are NaN, Infinity, and -Infinity for division by zero depending on the numerator).

For integers in the core instructions, I think it makes sense to return a division-by-zero error(current implementation-defined semantics are that both interpreters crash). Crashing is not helpful in terms of returning a readable error message.

> Exceptions are otherwise not a thing in Bril, so this would be a new concept.

This is referring only to core Bril right? Because they are a thing in the memory extension like in attempting to do an out-of-bounds access(The memory extension is probably also under-specified? Neither it's documentation nor it's blog post seem to mention that implementations will error when reading uninitialized data). So I don't think introducing a divide-by-zero error is too much of a surprise.

> It makes basic manipulations more complex because you have to worry about potential side effects for div and fdiv instructions.

If you want a fully compliant tool then they become more complex, however, one could always choose to take the `--ffast-math` approach and accept some level of incompatibility. In this way, one could always layer Undefined behavior on top of the current specification but one could not (with the current bril extensions) layer on an error for division-by-zero.

**Comment by sampsyo** [comment]
> This is referring only to core Bril right? Because they are a thing in the memory extension like in attempting to do an out-of-bounds access(The memory extension is probably also under-specified? Neither it's documentation nor it's blog post seem to mention that implementations will error when reading uninitialized data).

It's a little different: the spec says that these things *are errors* and that *programs should not do them* and that *programs that do these things are bad programs*. But it doesn't specify what implementations should do. That's intentional, so that users can't rely on specific behavior, such as immediate termination; implementations (such as efficient compilers) are free to do whatever they want to bad programs. *Helpful* implementations may *choose* to signal an error when this happens, but that's different from having it be required to do so.

Anyway, returning one of those FP results for `fdiv`-by-zero makes sense! But I think the above issue about freedom for implementations complicates the decision for integer `div`. I am not wild about the `ffast-math` approach, which is incredibly hard to describe from a semantics perspective in the real world…

**Comment by Pat-Lafon** [comment]
> the spec says that these things are errors and that programs should not do them and that programs that do these things are bad programs. But it doesn't specify what implementations should do. 

My understanding is that this is essentially undefined behavior(from my reading of https://blog.regehr.org/archives/213). So if the other errors listed in the Bril spec lead to undefined behavior, then I'm not sure why divide-by-zero should be treated differently. Then an implementation like `brilirs` can have an implementation-defined behavior where divide-by-zero executions and other "bad programs" return an error. 

In terms of freedom of implementations(specifically for efficient compilers), my understanding of the arithmetic section(https://capra.cs.cornell.edu/bril/lang/core.html?highlight=overflow#arithmetic) is that integer overflow is well-defined(this has come up before in #117, #133 with the `mat-mul.bril` benchmark) which I would think would limit an efficient compiler about as much as a divide-by-zero check.

**Comment by sampsyo** [comment]
Yep! This issue is just about deciding whether we want to leave it as UB or do something else. There are trade-offs, of course.

There is an important difference between overflow-as-wraparound and divide-by-zero-as-error: the first is pure and the second is a side effect. So if we require an error here, we would be preventing LICM on `div` instructions, for example.

**Comment by sampsyo** [comment]
OK, I've changed the docs to say that it is not allowed to divide by zero. It's just as disallowed as referencing an undefined variable or dereferencing a bad pointer in the memory extension. That means we don't specify a specific semantics, and implementations are allowed to just crash or whatever. But it also rules out LICM of `div` instructions, because it could cause good programs to become bad. But I think that is really the only sensible thing to do.
