### ISSUE TITLE
[brilirs] Unreachable assertion reached

### ISSUE THREAD

**Issue by oflatt** [sampsyo/bril#346]
Here's a bril program that causes an unreachable assertion to be fired in the brilirs interpreter:
```
# ARGS: 150
@main(n : int) {
	zero: int = const 0;
	output: int = call @recPrint n;
	print output;
}

@recPrint(n: int): int {
	zero: int = const 0;
	cond: bool = eq n zero;
	br cond .end .rec;
.rec:
	print n;
  one: int = const 1;
  next: int = sub n one;
	sum: int = call @recPrint next;
.end:
	ret sum;
}
```

And the json:
```
{
  "functions": [
    {
      "args": [
        {
          "name": "n",
          "type": "int"
        }
      ],
      "instrs": [
        {
          "dest": "zero",
          "op": "const",
          "type": "int",
          "value": 0
        },
        {
          "args": [
            "n"
          ],
          "dest": "output",
          "funcs": [
            "recPrint"
          ],
          "op": "call",
          "type": "int"
        },
        {
          "args": [
            "output"
          ],
          "op": "print"
        }
      ],
      "name": "main"
    },
    {
      "args": [
        {
          "name": "n",
          "type": "int"
        }
      ],
      "instrs": [
        {
          "dest": "zero",
          "op": "const",
          "type": "int",
          "value": 0
        },
        {
          "args": [
            "n",
            "zero"
          ],
          "dest": "cond",
          "op": "eq",
          "type": "bool"
        },
        {
          "args": [
            "cond"
          ],
          "labels": [
            "end",
            "rec"
          ],
          "op": "br"
        },
        {
          "label": "rec"
        },
        {
          "args": [
            "n"
          ],
          "op": "print"
        },
        {
          "dest": "one",
          "op": "const",
          "type": "int",
          "value": 1
        },
        {
          "args": [
            "n",
            "one"
          ],
          "dest": "next",
          "op": "sub",
          "type": "int"
        },
        {
          "args": [
            "next"
          ],
          "dest": "sum",
          "funcs": [
            "recPrint"
          ],
          "op": "call",
          "type": "int"
        },
        {
          "label": "end"
        },
        {
          "args": [
            "sum"
          ],
          "op": "ret"
        }
      ],
      "name": "recPrint",
      "type": "int"
    }
  ]
}
```

I'm not sure why. Removing the print in main causes the issue to disappear

**Comment by Pat-Lafon** [comment]
Not sure about the comment about the print but this seems like invalid bril no? When I copied the text to a file and went `bril2json < test.bril | brili 150` it errors on the last execution(because sum does not get set when n =0).

**Comment by oflatt** [comment]
Oops good catch! Thanks
Is there a bril typechecker or validator I'm supposed to be running?

**Comment by Pat-Lafon** [comment]
I mean I can probably provide a better error message here(I'm not sure if the `unreachable!()` adds much if any performance improvement anyways).

Not sure if the typecheckers are sophisticated enough to find this? It's probably observable via static analysis except that Bril's semantics allow for such code as long as it doesn't appear dynamically. The problem is not with the function, it's that it's called with `n=0`.

In general, `brili` is the validator per se as the canonical implementation. I try to keep `brilirs` equivalent to `brili` on all well-formed(non-erroring, correctly typed) Bril programs. There are only a few exceptions(programs with missing/erroneous type annotations and duplicate labels) I think.

**Comment by sampsyo** [comment]
Just a tiny bit of commentary: there is a type checker I would recommend, in [the `brilck` tool](https://capra.cs.cornell.edu/bril/tools/brilck.html). But as @Pat-Lafon suggests, it does not catch this, because it's kind of a dynamic thing:

```
$ bril2json < foo.bril | brilck
$
```

That should catch plenty of errors, but it will not catch partially-defined variables that lead to undefined reads on only some inputs. Those require a dynamic check.

One could imagine changing the language to require that all reads are dominated by a write, which would make this kind of thing statically checkable. But that is not currently required.

**Comment by oflatt** [comment]
Thanks!
I think for the purposes of eggcc I should implement this check
