### ISSUE TITLE
Fix the Rust interpreter for the new syntax

### ISSUE THREAD

**Issue by sampsyo** [sampsyo/bril#51]
A "fun" task for any Rustaceans out there: #49 introduced a breaking syntax change, and the `brilirs` interpreter needs updating to match. In particular, the main necessary change is looking for labels in an instruction's `labels` key rather than in `args`.

**Comment by sampsyo** [comment]
A good way to go about this might be to refactor the interpreter to use the new [Rust library](https://github.com/sampsyo/bril/tree/master/bril-rs) instead of its own deserializer.

**Comment by yati-sagade** [comment]
Thanks for making the course! This was a nice task to get familiar with bril. I've left `call` since it wasn't implemented here anyway and it would likely require some additional changes looking at the TypeScript implementation. I've also left out all the extensions except float, which was simple enough to implement.
