### ISSUE TITLE
Bril Type Error questions

### ISSUE THREAD

**Issue by Pat-Lafon** [sampsyo/bril#91]
2 benchmarks (perfect.bril and digital-root.bril) have ret instructions at the end of their main functions that return values despite them not having a return type. I guess this is a type error?

A more general question. From the type system perspective, if a function both returns a value and has a side effect, does it need to be called as a Value operation (because it returns something) or can it be called as an Effect operation (and just ignore the return value)?

**Comment by sampsyo** [comment]
1. Yeah, that's a good point—functions should not return a value if they don't have a return type declared. It's worth re-emphasizing that both of those benchmarks you mentioned have the weird `ret` in the `main` function, which isn't supposed to return anything. Maybe someday it would make sense to allow returning a value from main, but if we do that, then it would require declaring the return type before doing that.
2. The spec should be clearer about this, but I think the intent is that `call` *must* be used as a Value Operation if the function returns a value, i.e., return values are not ignorable.

**Comment by Pat-Lafon** [comment]
As I'm running the benchmarks with brilirs, I've noticed it breaks on lines like the following `v21: float = const 2;` because this looks like an integer literal being promoted to a float. Is the previous line allowed or should only `v21: float = const 2.0;` be valid?

**Comment by sampsyo** [comment]
Right, I noticed that too when fiddling around with it. I think the Right Thing to Do is to make that illegal, i.e., float constants must be floats like 42.0 and integer constants must be integers like 42 (maybe the docs need amending). Checking this is annoyingly hard in TypeScript because of JavaScript's all-float-all-the-time `number` type, but of course it's trivial with `serde_json`. So IMO let's leave it be.

**Comment by Pat-Lafon** [comment]
With #117 merged I'm closing this issue.
